// packages/api/src/routers/workspaces/invitations.router.ts
//
// ─────────────────────────────────────────────────────────────────────────────
// Workspace Invitations sub-router (F3a.3)
//
// Mounted at v1.public.workspace.invitations.* inside workspacesRouter.
// Implements the token-based invitation lifecycle:
//
//   list          — workspaceAdminProcedure (pending invitations of a workspace)
//   create        — workspaceAdminProcedure (issue invitation + outbox event)
//   revoke        — workspaceAdminProcedure (soft-revoke)
//   getByToken    — publicProcedure (accept page — BYPASSRLS)
//   accept        — protectedProcedure (logged-in user accepts — BYPASSRLS)
//   getMyPending  — protectedProcedure (bell badge: pending invitations for me)
//
// Token security:
//   • 48-byte crypto-random base64url (384 bits entropy) — generated by repo.
//   • Never exposed in logs (masked via invitationTokenService.maskToken).
//   • getByToken returns masked email + workspace info, NEVER the full token.
//
// RLS bypass:
//   • getByToken and accept use withServiceRoleConnection because the user
//     is not yet a workspace member at call time → RLS would hide the row.
//   • Every service-role usage is audit-logged.
//
// Outbox topics emitted:
//   workspace.invitation.created
//   workspace.invitation.revoked
//   workspace.invitation.accepted
//   workspace.member.added
// ─────────────────────────────────────────────────────────────────────────────

import crypto from "node:crypto";
import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { eq, and, isNull } from "drizzle-orm";

import { router, protectedProcedure, publicProcedure } from "../../trpc";
import { workspaceAdminProcedure } from "../../middleware/workspaceRoleProcedures";
import { withIdempotency } from "../../utils/idempotency";
import { withServiceRoleConnection } from "../../services/serviceRoleConnection";
import { maskEmail } from "../../services/invitationTokenService";
import {
  DrizzleWorkspaceInvitationsRepository,
  DuplicateActiveInvitationError,
} from "@repo/db";
import { users, workspaces, workspaceMembers, workspaceInvitations } from "@repo/db";
import {
  acceptInvitation,
  revokeInvitation,
  type WorkspaceRole,
} from "@repo/domain/workspaces";

// ─── Shared schemas ─────────────────────────────────────────────────────────

const IdSchema = z.string().uuid();
const IdempotencyKeySchema = z.string().uuid().optional();
const EmailSchema = z.string().email().max(254);
const TokenSchema = z.string().min(40).max(100); // base64url 64 chars typical

const InvitationRoleSchema = z.enum(["ADMIN", "MEMBER", "VIEWER"]);

// ─── Router ─────────────────────────────────────────────────────────────────

export const workspaceInvitationsRouter = router({
  // ── invitations.list (admin) ──────────────────────────────────────────────
  //
  // Returns active (pending, non-expired, non-revoked, non-accepted)
  // invitations for the workspace. Used by the Members tab "Pending
  // invitations" section.
  list: workspaceAdminProcedure
    .input(z.object({ workspaceId: IdSchema }))
    .query(async ({ input, ctx }) => {
      const repo = new DrizzleWorkspaceInvitationsRepository(ctx.infra.db);
      const invitations = await repo.findActiveByWorkspace(input.workspaceId);

      return invitations.map((inv) => ({
        id: inv.id,
        invitedEmail: inv.invitedEmail,
        role: inv.role,
        invitedByUserId: inv.invitedByUserId,
        expiresAt: inv.expiresAt.toISOString(),
        createdAt: inv.createdAt.toISOString(),
      }));
    }),

  // ── invitations.create (admin) ────────────────────────────────────────────
  //
  // Issues a new invitation. Token is generated by the repository (48-byte
  // crypto-random). Emits workspace.invitation.created outbox event.
  // Throws CONFLICT if an active invitation for the same email exists.
  create: workspaceAdminProcedure
    .input(
      z.object({
        workspaceId: IdSchema,
        email: EmailSchema,
        role: InvitationRoleSchema,
        idempotencyKey: IdempotencyKeySchema,
      }),
    )
    .mutation(async ({ input, ctx }) => {
      return withIdempotency(ctx, input.idempotencyKey, "v1", async () => {
        const normalizedEmail = input.email.trim().toLowerCase();

        // Check if user is already a member
        const existingUser = await ctx.infra.db.query.users.findFirst({
          where: eq(users.emailNormalized, normalizedEmail),
        });

        if (existingUser) {
          const existingMember =
            await ctx.infra.db.query.workspaceMembers.findFirst({
              where: and(
                eq(workspaceMembers.workspaceId, input.workspaceId),
                eq(workspaceMembers.userId, existingUser.id),
              ),
            });
          if (existingMember) {
            throw new TRPCError({
              code: "CONFLICT",
              message: "این کاربر از قبل عضو فضای کاری است.",
            });
          }
        }

        const repo = new DrizzleWorkspaceInvitationsRepository(ctx.infra.db);

        let invitation;
        try {
          invitation = await repo.create(
            {
              workspaceId: input.workspaceId,
              email: normalizedEmail,
              role: input.role,
              invitedByUserId: ctx.session.user.id,
              invitedUserId: existingUser?.id ?? null,
            },
            ctx.infra.db,
          );
        } catch (err) {
          if (err instanceof DuplicateActiveInvitationError) {
            throw new TRPCError({
              code: "CONFLICT",
              message: "دعوت فعالی برای این ایمیل قبلاً ارسال شده است.",
            });
          }
          throw err;
        }

        // Emit outbox event (atomic — same tx)
        await ctx.repos.outbox.append(ctx.infra.db, {
          eventId: crypto.randomUUID(),
          eventVersion: "v1",
          aggregateId: input.workspaceId,
          aggregateType: "workspace",
          type: "workspace.invitation.created",
          occurredAt: new Date(),
          correlationId: input.idempotencyKey ?? undefined,
          payload: {
            workspaceId: input.workspaceId,
            invitationId: invitation.id,
            invitedEmail: normalizedEmail,
            role: input.role,
            invitedBy: ctx.session.user.id,
            expiresAt: invitation.expiresAt.toISOString(),
          },
        });

        return {
          success: true,
          invitationId: invitation.id,
          expiresAt: invitation.expiresAt.toISOString(),
        };
      });
    }),

  // ── invitations.revoke (admin) ────────────────────────────────────────────
  //
  // Soft-revokes an invitation. Uses the domain revokeInvitation use case
  // for guard validation, then delegates to the repository.
  revoke: workspaceAdminProcedure
    .input(
      z.object({
        workspaceId: IdSchema,
        invitationId: IdSchema,
        idempotencyKey: IdempotencyKeySchema,
      }),
    )
    .mutation(async ({ input, ctx }) => {
      return withIdempotency(ctx, input.idempotencyKey, "v1", async () => {
        const repo = new DrizzleWorkspaceInvitationsRepository(ctx.infra.db);

        // Load invitation within RLS tx (admin has access).
        const invitation = await ctx.infra.db.query.workspaceInvitations.findFirst({
          where: and(
            eq(workspaceInvitations.id, input.invitationId),
            eq(workspaceInvitations.workspaceId, input.workspaceId),
          ),
        });

        // Domain guard
        const result = revokeInvitation({
          invitation: invitation
            ? {
                id: invitation.id,
                workspaceId: invitation.workspaceId,
                acceptedAt: invitation.acceptedAt,
                revokedAt: invitation.revokedAt,
              }
            : null,
        });

        if (!result.success) {
          const messages: Record<string, { code: any; message: string }> = {
            NOT_FOUND: { code: "NOT_FOUND", message: "دعوت یافت نشد." },
            ALREADY_ACCEPTED: {
              code: "BAD_REQUEST",
              message: "این دعوت قبلاً پذیرفته شده — قابل لغو نیست.",
            },
            ALREADY_REVOKED: {
              code: "BAD_REQUEST",
              message: "این دعوت قبلاً لغو شده است.",
            },
          };
          const err = messages[result.reason];
          throw new TRPCError({ code: err.code, message: err.message });
        }

        // Perform revoke
        await repo.revoke(input.invitationId, ctx.session.user.id, ctx.infra.db);

        // Outbox event
        await ctx.repos.outbox.append(ctx.infra.db, {
          eventId: crypto.randomUUID(),
          eventVersion: "v1",
          aggregateId: input.workspaceId,
          aggregateType: "workspace",
          type: "workspace.invitation.revoked",
          occurredAt: new Date(),
          correlationId: input.idempotencyKey ?? undefined,
          payload: {
            workspaceId: input.workspaceId,
            invitationId: input.invitationId,
            revokedBy: ctx.session.user.id,
          },
        });

        return { success: true, invitationId: input.invitationId };
      });
    }),

  // ── invitations.getByToken (public — no auth!) ────────────────────────────
  //
  // Used by the accept page to display invitation details before the user
  // decides to accept. Runs with BYPASSRLS because the user may not be a
  // workspace member yet.
  //
  // TODO(F3a.4 or F5): IP-based rate limit on getByToken to harden against
  // distributed token guessing. Token entropy (256+ bits) makes single-IP
  // guessing impractical, but bot-net brute force is still theoretically
  // possible. Hook into rateLimitMiddleware once it supports IP keying.
  getByToken: publicProcedure
    .input(z.object({ token: TokenSchema }))
    .query(async ({ input, ctx }) => {
      return withServiceRoleConnection(
        ctx.infra.db,
        {
          procedure: "invitations.getByToken",
          userId: ctx.session?.user?.id,
          reason: "User not yet workspace member — RLS would hide invitation row",
        },
        async (tx) => {
          const repo = new DrizzleWorkspaceInvitationsRepository(tx);
          const invitation = await repo.findByToken(input.token);

          if (!invitation) {
            throw new TRPCError({
              code: "NOT_FOUND",
              message: "این دعوت معتبر نیست.",
            });
          }

          // Load workspace name + slug for UI
          const workspace = await tx.query.workspaces.findFirst({
            where: eq(workspaces.id, invitation.workspaceId),
          });

          // Load inviter displayName
          const inviter = await tx.query.users.findFirst({
            where: eq(users.id, invitation.invitedByUserId),
          });

          const now = new Date();
          const isExpired = invitation.expiresAt < now;
          const isRevoked = invitation.revokedAt !== null;

          // Check if current user (if authenticated) already accepted
          let isAcceptedByCurrentUser = false;
          if (
            ctx.session?.user?.id &&
            invitation.acceptedAt !== null &&
            invitation.acceptedByUserId === ctx.session.user.id
          ) {
            isAcceptedByCurrentUser = true;
          }

          return {
            workspaceName: workspace?.name ?? "فضای کاری",
            workspaceSlug: workspace?.slug ?? "",
            invitedEmailMasked: maskEmail(invitation.invitedEmail),
            role: invitation.role as WorkspaceRole,
            inviterDisplayName: inviter?.displayName ?? "کاربر",
            expiresAt: invitation.expiresAt.toISOString(),
            isRevoked,
            isExpired,
            isAcceptedByCurrentUser,
          };
        },
      );
    }),

  // ── invitations.accept (protected — logged-in user) ───────────────────────
  //
  // Accepts an invitation. Validates email match, creates workspace
  // membership, marks invitation as accepted — all in one atomic tx with
  // BYPASSRLS. Emits two outbox events: invitation.accepted + member.added.
  accept: protectedProcedure
    .input(
      z.object({
        token: TokenSchema,
        idempotencyKey: IdempotencyKeySchema,
      }),
    )
    .mutation(async ({ input, ctx }) => {
      return withIdempotency(ctx, input.idempotencyKey, "v1", async () => {
        return withServiceRoleConnection(
          ctx.infra.db,
          {
            procedure: "invitations.accept",
            userId: ctx.session.user.id,
            reason: "User not yet workspace member — RLS would hide invitation row",
          },
          async (tx) => {
            const repo = new DrizzleWorkspaceInvitationsRepository(tx);

            // Load invitation with row lock (prevent concurrent accept race)
            const invitation = await repo.findByToken(input.token);

            // Load the accepting user's email for match check
            const acceptingUser = await tx.query.users.findFirst({
              where: eq(users.id, ctx.session.user.id),
            });
            if (!acceptingUser) {
              throw new TRPCError({
                code: "INTERNAL_SERVER_ERROR",
                message: "خطای داخلی: کاربر یافت نشد.",
              });
            }

            // Check workspace not soft-deleted
            let workspaceDeleted = false;
            if (invitation) {
              const ws = await tx.query.workspaces.findFirst({
                where: eq(workspaces.id, invitation.workspaceId),
              });
              workspaceDeleted = ws?.deletedAt !== null && ws?.deletedAt !== undefined;
            }

            // Domain use case — pure validation
            const result = acceptInvitation({
              invitation: invitation
                ? {
                    id: invitation.id,
                    workspaceId: invitation.workspaceId,
                    invitedEmail: invitation.invitedEmail,
                    role: invitation.role,
                    expiresAt: invitation.expiresAt,
                    acceptedAt: invitation.acceptedAt,
                    acceptedByUserId: invitation.acceptedByUserId,
                    revokedAt: invitation.revokedAt,
                  }
                : null,
              acceptingUserId: ctx.session.user.id,
              acceptingUserEmail: acceptingUser.emailNormalized,
              workspaceDeleted,
              now: new Date(),
            });

            if (!result.success) {
              const errorMap: Record<string, { code: any; message: string }> = {
                NOT_FOUND: {
                  code: "NOT_FOUND",
                  message: "این دعوت معتبر نیست.",
                },
                REVOKED: {
                  code: "BAD_REQUEST",
                  message: "این دعوت لغو شده است.",
                },
                EXPIRED: {
                  code: "BAD_REQUEST",
                  message: "این دعوت منقضی شده است.",
                },
                ALREADY_ACCEPTED_BY_OTHER: {
                  code: "FORBIDDEN",
                  message: "این دعوت قبلاً پذیرفته شده است.",
                },
                WORKSPACE_DELETED: {
                  code: "NOT_FOUND",
                  message: "این فضای کاری دیگر در دسترس نیست.",
                },
                EMAIL_MISMATCH: {
                  code: "FORBIDDEN",
                  message:
                    "این دعوت برای ایمیل دیگری ارسال شده. با حساب درست وارد شوید.",
                },
              };
              const err = errorMap[result.reason];
              throw new TRPCError({ code: err.code, message: err.message });
            }

            // Idempotent re-click: already accepted by this user
            if (result.alreadyAccepted) {
              return {
                success: true,
                workspaceId: result.workspaceId,
                alreadyAccepted: true,
              };
            }

            // ── Atomic writes ─────────────────────────────────────────────

            // 1. Mark invitation as accepted
            await repo.markAccepted(invitation!.id, ctx.session.user.id, tx);

            // 2. Insert workspace membership
            const now = new Date();
            await tx.insert(workspaceMembers).values({
              workspaceId: invitation!.workspaceId,
              userId: ctx.session.user.id,
              role: invitation!.role as WorkspaceRole,
              joinedAt: now,
              invitedBy: invitation!.invitedByUserId,
            });

            // 3. Outbox: workspace.invitation.accepted
            const outboxRepo = ctx.repos.outbox;
            await outboxRepo.append(tx, {
              eventId: crypto.randomUUID(),
              eventVersion: "v1",
              aggregateId: invitation!.workspaceId,
              aggregateType: "workspace",
              type: "workspace.invitation.accepted",
              occurredAt: now,
              correlationId: input.idempotencyKey ?? undefined,
              payload: {
                workspaceId: invitation!.workspaceId,
                invitationId: invitation!.id,
                acceptedByUserId: ctx.session.user.id,
                role: invitation!.role,
              },
            });

            // 4. Outbox: workspace.member.added
            await outboxRepo.append(tx, {
              eventId: crypto.randomUUID(),
              eventVersion: "v1",
              aggregateId: invitation!.workspaceId,
              aggregateType: "workspace",
              type: "workspace.member.added",
              occurredAt: now,
              correlationId: input.idempotencyKey ?? undefined,
              payload: {
                workspaceId: invitation!.workspaceId,
                userId: ctx.session.user.id,
                role: invitation!.role,
                addedBy: invitation!.invitedByUserId,
              },
            });

            return {
              success: true,
              workspaceId: invitation!.workspaceId,
              alreadyAccepted: false,
            };
          },
        );
      });
    }),

  // ── invitations.getMyPending (protected) ──────────────────────────────────
  //
  // Returns all pending invitations for the current user's email, across
  // ALL workspaces. Used by the notifications bell badge in F4.
  // Runs with BYPASSRLS because the user may not be a member of those
  // workspaces yet.
  getMyPending: protectedProcedure.query(async ({ ctx }) => {
    return withServiceRoleConnection(
      ctx.infra.db,
      {
        procedure: "invitations.getMyPending",
        userId: ctx.session.user.id,
        reason: "Cross-workspace lookup for invitations addressed to user email",
      },
      async (tx) => {
        // Get current user email
        const user = await tx.query.users.findFirst({
          where: eq(users.id, ctx.session.user.id),
        });
        if (!user) {
          return [];
        }

        const repo = new DrizzleWorkspaceInvitationsRepository(tx);
        const invitations = await repo.findActiveByEmail(user.emailNormalized);

        // Enrich with workspace name for UI
        const results = [];
        for (const inv of invitations) {
          const ws = await tx.query.workspaces.findFirst({
            where: and(
              eq(workspaces.id, inv.workspaceId),
              isNull(workspaces.deletedAt),
            ),
          });
          if (!ws) continue; // workspace deleted — skip

          results.push({
            id: inv.id,
            workspaceName: ws.name,
            workspaceSlug: ws.slug,
            role: inv.role,
            invitedByUserId: inv.invitedByUserId,
            expiresAt: inv.expiresAt.toISOString(),
            createdAt: inv.createdAt.toISOString(),
          });
        }

        return results;
      },
    );
  }),
});
